[CmdletBinding()]
param(
    [string]$OutputDirectory = (Join-Path $env:USERPROFILE 'Documents\CounterIQ-License-Authority'),
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

if (-not $IsWindows -and $PSVersionTable.PSEdition -eq 'Core') {
    throw 'Run this script on Windows.'
}

$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$dartConfigPath = Join-Path $projectRoot 'lib\config\license_public_key.dart'
$privatePfxPath = Join-Path $OutputDirectory 'counteriq-license-private.pfx'
$publicCerPath = Join-Path $OutputDirectory 'counteriq-license-public.cer'

if ((Test-Path $privatePfxPath) -and -not $Force) {
    throw @"
A CounterIQ private licensing key already exists here:
$privatePfxPath

Do NOT generate a new authority for normal use. Existing customer licenses rely on the same key.
Use the existing PFX, or run with -Force only if you intentionally want to rotate the licensing authority.
"@
}

New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

Write-Host ''
Write-Host 'CounterIQ Offline Licensing Authority Setup' -ForegroundColor Cyan
Write-Host 'Create a strong password for the private PFX.' -ForegroundColor Yellow
Write-Host 'The password is never written to disk by this script.' -ForegroundColor Yellow
$securePassword = Read-Host 'PFX password' -AsSecureString

$cert = $null
try {
    $cert = New-SelfSignedCertificate `
        -Subject 'CN=CounterIQ Offline License Signing' `
        -FriendlyName 'CounterIQ Offline License Signing' `
        -Type Custom `
        -KeyAlgorithm RSA `
        -KeyLength 3072 `
        -HashAlgorithm SHA256 `
        -KeyExportPolicy Exportable `
        -KeyUsage DigitalSignature `
        -CertStoreLocation 'Cert:\CurrentUser\My' `
        -NotAfter (Get-Date).AddYears(20)

    Export-PfxCertificate `
        -Cert $cert `
        -FilePath $privatePfxPath `
        -Password $securePassword `
        -ChainOption EndEntityCertOnly `
        -Force | Out-Null

    Export-Certificate `
        -Cert $cert `
        -FilePath $publicCerPath `
        -Type CERT `
        -Force | Out-Null

    $certificateBase64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($publicCerPath))
    $thumbprint = $cert.Thumbprint.ToUpperInvariant()

    $dart = @"
/// Public certificate used to verify CounterIQ offline machine licenses.
///
/// GENERATED by tools/license/setup_license_keys.ps1.
/// This is PUBLIC material and is safe to ship inside CounterIQ.
/// Never place the matching private PFX or its password in the app/project.
class LicensePublicKeyConfig {
  static const String certificateDerBase64 = '$certificateBase64';
  static const String certificateThumbprint = '$thumbprint';

  static bool get isConfigured => certificateDerBase64.trim().isNotEmpty;

  const LicensePublicKeyConfig._();
}
"@

    [IO.File]::WriteAllText(
        $dartConfigPath,
        $dart,
        (New-Object Text.UTF8Encoding($false))
    )
}
finally {
    if ($null -ne $cert) {
        # Do not leave an extra exportable private key in the Windows certificate store.
        $storePath = "Cert:\CurrentUser\My\$($cert.Thumbprint)"
        if (Test-Path $storePath) {
            Remove-Item $storePath -Force
        }
    }
}

Write-Host ''
Write-Host 'CounterIQ licensing authority created.' -ForegroundColor Green
Write-Host "Private PFX : $privatePfxPath"
Write-Host "Public CER  : $publicCerPath"
Write-Host "App public key updated: $dartConfigPath"
Write-Host ''
Write-Host 'IMPORTANT:' -ForegroundColor Yellow
Write-Host '1. Keep the PFX password separate from the PFX file.'
Write-Host '2. Back up the password-protected PFX. Losing it means you cannot issue new licenses compatible with existing builds.'
Write-Host '3. Never send the private PFX to a customer and never put it in the CounterIQ project/MSIX.'
