library;
import 'package:enterprise_pos/models/product_unit.dart';

/// Server-side field errors, mapped back to the document line they belong to.
///
/// A 422 arrives in two very different situations and both need the same
/// answer to "which cart line is the server complaining about?":
///
///   * live, while the cashier still has the cart on screen — the bag comes
///     straight off [ApiException.body];
///   * hours later, on the offline review screen — by then the response is
///     long gone and all that survives is the text OfflineSyncService wrote
///     into the queue row's `last_error`.
///
/// Both parsers live here, next to each other, so the recorded format and the
/// format that is read back can never drift apart. They are pure functions so
/// they can be tested without a widget tree.

/// One field error, resolved to a line index.
class LineError {
  /// Position in the request array — the N in `items.N.quantity`.
  final int index;

  /// The line field that was rejected (`quantity`, `received_qty`, …).
  final String field;

  /// The server's own message, verbatim. Never reworded: it names the unit,
  /// and the cashier needs that detail to know what to do.
  final String message;

  const LineError({
    required this.index,
    required this.field,
    required this.message,
  });

  /// The rule the server just asserted, when this error is the decimal
  /// rejection — otherwise null.
  ///
  /// A decimal rejection is the server stating that this line's unit does not
  /// allow a fraction. That is newer and more authoritative than whatever the
  /// line was carrying (a cache row from before the unit changed, or nothing
  /// at all), so it is worth writing back onto the line.
  QuantityRule? get assertedRule {
    if (!isDecimalRejection(message)) return null;
    return QuantityRule(unitName: unitNameIn(message) ?? '', allowDecimal: false);
  }

  /// What to show beside the line. The field name is only worth spelling out
  /// when it is not the obvious one — a quantity complaint next to a quantity
  /// column does not need the word "quantity" in front of it.
  String get display => field == 'quantity' ? message : '$field: $message';

  @override
  String toString() => 'LineError($index.$field: $message)';
}

/// The prefix every line-scoped key starts with, in both sales and purchases.
const String _itemsPrefix = 'items.';

/// Parses a Laravel-style validation bag — `{"items.0.quantity": ["…"]}` —
/// into line errors. Keys that are not line-scoped are ignored; use
/// [flattenBag] when the whole bag is wanted.
List<LineError> parseValidationBag(Object? errors) {
  if (errors is! Map) return const [];
  final out = <LineError>[];
  for (final entry in errors.entries) {
    final key = entry.key.toString();
    if (!key.startsWith(_itemsPrefix)) continue;
    final parts = key.split('.');
    if (parts.length < 3) continue;
    final index = int.tryParse(parts[1]);
    if (index == null) continue;
    out.add(LineError(
      index: index,
      field: parts.sublist(2).join('.'),
      message: _messageOf(entry.value),
    ));
  }
  return out;
}

/// Every entry in a validation bag as `key` → single message string, in the
/// order the server sent them.
Map<String, String> flattenBag(Object? errors) {
  if (errors is! Map) return const {};
  return {
    for (final entry in errors.entries)
      entry.key.toString(): _messageOf(entry.value),
  };
}

/// Renders a bag for storage in the offline queue's `last_error`, one
/// `key: message` per line. [parseStoredLineErrors] is the inverse.
String formatBagForStorage(Object? errors) =>
    flattenBag(errors).entries.map((e) => '${e.key}: ${e.value}').join('\n');

/// Reads back what [formatBagForStorage] wrote, ignoring any other prose in
/// the stored text (the humanized first line, for instance).
List<LineError> parseStoredLineErrors(String? storedError) {
  if (storedError == null || storedError.isEmpty) return const [];
  final pattern = RegExp(r'^items\.(\d+)\.([\w.]+):\s*(.+)$');
  final out = <LineError>[];
  for (final line in storedError.split('\n')) {
    final match = pattern.firstMatch(line.trim());
    if (match == null) continue;
    final index = int.tryParse(match.group(1)!);
    if (index == null) continue;
    out.add(LineError(
      index: index,
      field: match.group(2)!,
      message: match.group(3)!.trim(),
    ));
  }
  return out;
}

/// Whether [message] is the quantity-granularity rejection.
///
/// Matched on the server's wording, which is generated by
/// `units.Rule.Message()` in Go and mirrored by [QuantityRule.message] here.
/// If that sentence is ever reworded, both sides and this check move together.
bool isDecimalRejection(String message) =>
    message.startsWith('Decimal quantity is not allowed');

/// The unit name quoted inside a rejection message, or null.
String? unitNameIn(String message) =>
    RegExp(r'unit "([^"]+)"').firstMatch(message)?.group(1);

String _messageOf(Object? value) {
  if (value is List && value.isNotEmpty) {
    return value.map((m) => m.toString()).join(' ');
  }
  return value?.toString() ?? '';
}
